"use client";
import { useEffect, useState } from "react";

type Item = { name: string; points: number; rank: number };
export type CeremonyTvData = { teams: Item[]; players: Item[]; pronostics: Item[]; quiz: Item[]; services: Item[]; babyfoot: Item[]; bracket: { phase: string; a: string; b: string; scoreA: number | null; scoreB: number | null }[]; stats: Record<string, number> };
const slides = ["opening","numbers","team-race","teams","player-race","pronostics","quiz","services","bracket","babyfoot","hall","moments","thanks","rewards"];
const durations = [24000,26000,38000,36000,38000,30000,30000,30000,34000,32000,32000,26000,24000,48000];
const titles: Record<string,string> = { opening:"OUVERTURE", numbers:"LA COMPÉTITION EN CHIFFRES", "team-race":"LA COURSE DES ÉQUIPES", teams:"CLASSEMENT FINAL", "player-race":"LA COURSE INDIVIDUELLE", pronostics:"PRONOSTICS", quiz:"QUIZ", services:"LES SERVICES", bracket:"LE DERNIER ACTE", babyfoot:"CLASSEMENT BABY-FOOT", hall:"HALL OF FAME", moments:"MOMENTS FORTS", thanks:"MERCI", rewards:"RÉCOMPENSES" };

function Rows({ items, unit, limit = 8 }: { items: Item[]; unit: string; limit?: number }) { return <div className="tv-ranking"><div className="tv-ranking-head"><span>{unit}</span><span>POINTS</span></div>{items.slice(0,limit).map((x,i)=><div className={`tv-rank-row ${i===0?"is-winner":""}`} key={`${x.name}-${x.rank}`}><b>{String(x.rank).padStart(2,"0")}</b><span>{x.name}</span><strong>{Math.round(x.points)}</strong></div>)}</div>; }
function Podium({ items, unit }: { items: Item[]; unit: string }) { return <div className="tv-podium">{[items[1],items[0],items[2]].filter(Boolean).map(x=><div className={`tv-podium-place place-${x.rank}`} key={x.name}><small>{String(x.rank).padStart(2,"0")}</small><b>{x.name}</b><strong>{Math.round(x.points)} <em>PTS</em></strong><i>{unit}</i></div>)}</div>; }
function Race({ items, unit }: { items: Item[]; unit: string }) { return <div className="tv-race">{items.slice(0,8).map((x,i)=><div className="tv-race-row" key={x.name}><b>{String(i+1).padStart(2,"0")}</b><span>{x.name}</span><div><i style={{width:`${Math.max(18,100-i*9)}%`}} /></div><strong>{Math.round(x.points)}</strong><small>{unit}</small></div>)}</div>; }

export function FinalCeremonyTv({ data }: { data: CeremonyTvData }) {
  const [index,setIndex]=useState(0); const [loop,setLoop]=useState(0);
  useEffect(()=>{document.body.classList.add("tv-ceremony-active");return()=>document.body.classList.remove("tv-ceremony-active")},[]);
  useEffect(()=>{const t=window.setTimeout(()=>{if(index===slides.length-1){setIndex(0);setLoop(x=>x+1)}else setIndex(x=>x+1)},durations[index]);return()=>window.clearTimeout(t)},[index]);
  const key=slides[index], champ=data.teams[0], player=data.players[0], prono=data.pronostics[0], quiz=data.quiz[0], service=data.services[0], baby=data.babyfoot[0];
  const facts: Record<string,string>={matches:"MATCHS",pronostics:"PRONOSTICS",quiz:"QUIZ",participants:"PARTICIPANTS",services:"SERVICES",babyfoot:"MATCHS DE BABY-FOOT"};
  const confetti=index===0?<div className="tv-confetti">{Array.from({length:34},(_,i)=><i key={i} style={{left:`${(i*29)%100}%`,animationDelay:`${i%9*90}ms`}} />)}</div>:null;
  return <main className="tv-ceremony"><div className="tv-atmosphere"/><div className="tv-orbit orbit-one"/><div className="tv-orbit orbit-two"/><div className="tv-topline"><span>CANAL CUP <b>2026</b></span><span>ÉDITION FINALE · DIFFUSION CONTINUE</span></div>
    <section className="tv-slide" key={`${key}-${loop}`}><div className="tv-kicker">{titles[key]}</div>
    {key==="opening"&&<div className="tv-opening"><div className="tv-cup-mark">CC</div><h1>CANAL CUP<br/><span>2026</span></h1><p>EST TERMINÉE</p><div className="tv-rule"/><small>Merci à toutes et tous pour cette édition.</small></div>}
    {key==="numbers"&&<div className="tv-content"><h2>Une édition qui a<br/><span>fait vibrer le bureau.</span></h2><div className="tv-stat-grid">{Object.entries(data.stats).map(([k,v],i)=><div className="tv-stat" style={{animationDelay:`${i*120}ms`}} key={k}><strong>{v}</strong><span>{facts[k]}</span></div>)}</div></div>}
    {key==="team-race"&&<div className="tv-content"><h2>La course du<br/><span>classement général.</span></h2><p className="tv-subtitle">Les positions finales, révélées une à une.</p><Race items={data.teams} unit="ÉQUIPES"/></div>}
    {key==="teams"&&<div className="tv-content"><div className="tv-section-title"><h2>Le podium<br/><span>Canal Cup.</span></h2><strong>ÉQUIPES</strong></div><Podium items={data.teams} unit="ÉQUIPES"/><Rows items={data.teams} unit="CLASSEMENT COMPLET" limit={7}/></div>}
    {key==="player-race"&&<div className="tv-content"><h2>Chaque point compte.<br/><span>Chaque joueur aussi.</span></h2><Race items={data.players} unit="JOUEURS"/><div className="tv-reveal">Champion individuel <b>{player?.name}</b></div></div>}
    {key==="pronostics"&&<div className="tv-content"><div className="tv-section-title"><h2>Les plus<br/><span>visionnaires.</span></h2><strong>JOUEURS</strong></div><Podium items={data.pronostics} unit="JOUEURS"/><Rows items={data.pronostics} unit="TOP 10" limit={10}/></div>}
    {key==="quiz"&&<div className="tv-content"><div className="tv-section-title"><h2>La culture<br/><span>du jeu.</span></h2><strong>JOUEURS</strong></div><Podium items={data.quiz} unit="JOUEURS"/><Rows items={data.quiz} unit="TOP 10" limit={10}/></div>}
    {key==="services"&&<div className="tv-content"><div className="tv-section-title"><h2>La compétition<br/><span>en équipe.</span></h2><strong>SERVICES</strong></div><Rows items={data.services} unit="CLASSEMENT FINAL" limit={10}/><div className="tv-reveal">Service en tête <b>{service?.name}</b></div></div>}
    {key==="bracket"&&<div className="tv-content"><h2>Le dernier acte<br/><span>s'est joué ici.</span></h2><div className="tv-bracket">{["semi","third","final"].map(p=><div key={p}><h3>{p==="semi"?"DEMI-FINALES":p==="third"?"PETITE FINALE":"FINALE"}</h3>{data.bracket.filter(m=>m.phase===p).map((m,i)=><div className={`tv-match-card ${p==="final"?"is-final":""}`} key={i}><span>{m.a}<b>{m.scoreA??"·"}</b></span><span>{m.b}<b>{m.scoreB??"·"}</b></span></div>)}</div>)}</div><div className="tv-reveal">Champion Baby-foot <b>{baby?.name}</b></div></div>}
    {key==="babyfoot"&&<div className="tv-content"><div className="tv-section-title"><h2>Classement<br/><span>Baby-foot.</span></h2><strong>BINÔMES</strong></div><Podium items={data.babyfoot} unit="BINÔMES"/><Rows items={data.babyfoot} unit="CLASSEMENT COMPLET" limit={10}/></div>}
    {key==="hall"&&<div className="tv-content"><h2>Les noms qui<br/><span>restent.</span></h2><div className="tv-hall">{[["CHAMPION CANAL CUP",champ?.name],["CHAMPION BABY-FOOT",baby?.name],["VAINQUEUR PRONOSTICS",prono?.name],["VAINQUEUR QUIZ",quiz?.name],["MEILLEUR SERVICE",service?.name]].filter(([,v])=>v).map(([t,v])=><div className="tv-hall-card" key={t}><span>{t}</span><strong>{v}</strong></div>)}</div></div>}
    {key==="moments"&&<div className="tv-content tv-moments"><h2>Une édition<br/><span>inoubliable.</span></h2><div className="tv-quote">Des matchs, des retournements, des points disputés jusqu'au bout.</div><div className="tv-moment-line"><b>{data.stats.matches}</b><span>matchs officiels<br/>pour écrire l'histoire.</span></div></div>}
    {key==="thanks"&&<div className="tv-thanks"><div className="tv-cup-mark">CC</div><h2>Merci à tous<span> !</span></h2><p>Rendez-vous en 2030.</p></div>}
    {key==="rewards"&&<div className="tv-rewards"><div>À RETENIR</div><h2>Les récompenses<br/><span>sont disponibles.</span></h2><div className="tv-rule"/><p>Passez récupérer vos lots<br/>auprès du service Marketing.</p><strong>BRAVO À TOUTES ET TOUS</strong></div>}
    </section><div className="tv-progress"><span style={{width:`${(index+1)/slides.length*100}%`}}/></div><div className="tv-slide-count">{String(index+1).padStart(2,"0")} / {String(slides.length).padStart(2,"0")}</div>{confetti}</main>;
}
